# fly.toml app configuration file generated for organizedbag on 2024-01-02T13:26:13-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "organizedbag"
primary_region = "scl"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "anoningyou/organizedbag:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
